name: Add new issues to the Happy Prime project board.

on:
  issues:
    types:
    - opened
  workflow_call:
    secrets:
      AMIABOT_BOT_TOKEN:
        required: true

jobs:
  add-to-project:
    name: Add issue to project board.
    runs-on: ubuntu-latest
    environment: paperplane
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/happyprime/projects/5
          github-token: ${{ secrets.AMIABOT_BOT_TOKEN }}
