name: WP.org Plugin Check

on:
  workflow_call:
    inputs:
      php-version:
        type: string
        description: 'PHP version to use'
        required: true
        default: '8.3'
      include_composer_dependencies:
        description: "Setup composer dependencies"
        required: false
        type: boolean
        default: true

# The GITHUB_TOKEN used by Dependabot has read-only permissions
# by default, so we provide write permissions to this workflow
# so that comments can be left on the pull request.
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions
permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        coverage: none
        tools: wp-cli

    - name: Run composer build
      if: inputs.include_composer_dependencies == true
      run: |
        composer install --no-dev --no-progress --optimize-autoloader
      env:
        GITHUB_TOKEN: ""  # override any job-level tokens so Composer skips validation
        COMPOSER_AUTH: ""

    - name: Install latest version of dist-archive-command
      run: wp package install wp-cli/dist-archive-command:3.1.0

    - name: Capture the plugin slug
      run: echo "PLUGIN_SLUG=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV

    - name: Build plugin
      id: build
      run: |
        wp dist-archive .  "${{ runner.temp }}/${{ env.PLUGIN_SLUG }}.zip" --create-target-dir --plugin-dirname=${{ env.PLUGIN_SLUG }}
        unzip "${{ runner.temp }}/${{ env.PLUGIN_SLUG }}.zip" -d "${{ runner.temp }}/build"

    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1.1.5
      with:
        build-dir: "${{ runner.temp }}/build/${{ env.PLUGIN_SLUG }}"
